import uuid from "react-uuid";

const FeaturesData = [
  {
    id: uuid(),
    name: "Search",
    description:
      "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    icon: require("../icons/3.png"),
  },
  {
    id: uuid(),
    name: "Select",
    description:
      "Choose from thousands of options generated by the slogan maker that fit your needs.",
    icon: require("../icons/1.png"),
  },
  {
    id: uuid(),
    name: "Stand out",
    description: "Congrats on your new slogan. It's time to win the world!",
    icon: require("../icons/2.png"),
  },
];
export { FeaturesData };
